#pragma once
#include"Appliances.h"

//#include"Artistic_literature.h"
//#include"Book.h"
#include"Clothing.h"
#include"Electronic_technic.h"
#include"Errors.h"
#include"ExceptionBase.h"
#include"Exception_Contr.h"
#include"Exception_File.h"
#include"Exception_vvod.h"
#include"Footwear.h"
//#include"Header.h"
#include"Item.h"
#include"Ring.h"
#include"Reseter.h"
//#include"Scientific_literature.h"
#include"Sport_Equipment.h"
#include"Technic.h"
#include"Interface.h"